
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[208] =
    {   0,
        0,    0,    0,    0,   90,   86,   85,   85,   72,   86,
       42,   43,   86,   75,   76,   40,   38,   82,   39,   81,
       41,   31,   31,   83,   84,   68,   70,   69,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   79,   80,   45,   77,   44,   78,   88,   88,
       85,   71,    0,   53,   60,   54,   48,    0,   51,   63,
       49,   64,   50,    0,    2,    1,   52,    0,   31,    0,
       37,    0,    0,   73,   62,   46,   66,   65,   67,   47,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   14,   16,   28,   28,   28,   28,   28,   28,   28,

       28,   28,   28,   28,   56,   55,   61,   87,   29,   59,
       30,   74,    1,    0,   35,    0,   32,    0,   33,    0,
       34,    0,   57,   58,   28,   28,   28,   28,   28,   28,
       28,   12,   28,   28,   28,   28,   19,   28,   28,   28,
       28,   28,   28,   28,   27,   35,    0,   34,    0,   28,
        4,    5,   28,   28,   28,   10,   28,   13,   15,   28,
       28,   28,   28,   28,   28,   28,   28,   26,    0,    0,
       36,    3,    6,   28,    9,   28,   28,   28,   28,   21,
       28,   28,   28,   28,   28,   28,   28,   17,   28,   28,
       22,   23,   24,   25,   28,    8,   28,   28,   20,   28,

       28,   28,    7,   28,   18,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       35,   42,   43,   44,   45,   46,   47,   48,   49,   35,
       50,    1,   51,   52,   53,    1,   54,   55,   56,   57,

       58,   59,   60,   61,   62,   35,   63,   64,   65,   66,
       67,   68,   35,   69,   70,   71,   72,   73,   74,   48,
       75,   35,   76,   77,   78,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[79] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    4,    4,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        6,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    7,    4,    4,    4,    4,    4,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    6,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1
    } ;

static const flex_int16_t yy_base[217] =
    {   0,
        0,    0,  233,  232,  242, 1133,   77,   79,  214,    0,
      213,   76,    0, 1133, 1133,  203,   72, 1133,   71,  206,
       75,  114,   87,  169, 1133,   74,  163,   65,   91,   95,
      125,  105,  153,  135,  134,  180,  186,  196,  206,  211,
      234,  248, 1133, 1133,  154, 1133,   63, 1133, 1133,  161,
       90, 1133,  161, 1133, 1133, 1133,  135,  145, 1133, 1133,
     1133, 1133, 1133,  135, 1133,    0, 1133,  258,  272,   99,
     1133,  138,   93, 1133, 1133,  115, 1133, 1133, 1133,  114,
        0,  165,  278,  294,  300,  304,  310,  328,  338,  332,
      342,  348,  359,  365,  369,  376,  392,  404,  408,  412,

      417,  437,  443,  447, 1133, 1133, 1133, 1133, 1133, 1133,
     1133, 1133,    0,  455,  473,  488,  101,  109,  191,  216,
       79,   83, 1133, 1133,  478,  495,  500,  504,  510,  524,
      538,  463,  542,  559,  566,  570,  574,  591,  597,  601,
      605,  619,  623,  630,  651,  657,    0,  179,  666,  678,
      682,  686,  690,  699,  703,  707,  711,  718,  729,  733,
      739,  747,  759,  767,  775,  779,  793,  805,   62,  809,
     1133,  820,  824,  828,  833,  837,  843,  849,  856,  864,
      876,  882,  886,  900,  892,  904,  919,  926,  945,  949,
      932,  963,  970,  974,  978,  983,  991,  996, 1000, 1008,

     1012, 1023, 1028, 1037, 1041, 1056, 1133, 1098, 1102, 1105,
     1108, 1114, 1118, 1122, 1126,   97
    } ;

static const flex_int16_t yy_def[217] =
    {   0,
      207,    1,  208,  208,  207,  207,  207,  207,  207,  209,
      207,  207,  210,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  211,  211,
      211,  211,  211,   31,   31,  211,  211,  211,  211,  211,
      211,  211,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  209,  207,  207,  207,  207,  210,  207,  207,
      207,  207,  207,  207,  207,  212,  207,  207,  207,  207,
      207,  207,  213,  207,  207,  207,  207,  207,  207,  207,
      214,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  211,

      211,  211,  211,  211,  207,  207,  207,  207,  207,  207,
      207,  207,  212,  207,  207,  207,  207,  207,  207,  207,
      215,  213,  207,  207,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  207,  216,  215,  207,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  216,  207,
      207,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  211,

      211,  211,  211,  211,  211,  211,    0,  207,  207,  207,
      207,  207,  207,  207,  207,  207
    } ;

static const flex_int16_t yy_nxt[1212] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   23,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   29,   36,   29,   29,   29,   37,   29,   29,
       38,   39,   40,   41,   29,   42,   29,   29,   29,   43,
       44,   45,    6,   29,   30,   31,   32,   33,   34,   35,
       29,   36,   29,   29,   37,   29,   29,   38,   39,   40,
       41,   29,   42,   29,   29,   46,   47,   48,   51,   51,
       51,   51,   55,   60,   62,   65,  106,   75,   79,   80,
       66,   51,   51,  147,   63,   61,   76,   77,   67,   56,

      169,   68,  149,   69,   69,   69,   69,   81,   81,   81,
       81,   81,   81,   81,   81,  117,  117,  117,  117,  149,
       71,   81,   81,   81,   81,  117,  117,   57,   68,  149,
       69,   69,   69,   69,   87,  207,   83,  124,  123,  107,
       70,   81,   81,   81,   81,  122,  149,   71,   71,  112,
       84,  118,  111,   72,  119,  119,  119,   85,  110,   82,
       89,   73,   87,   83,   86,  109,   82,   82,   70,   81,
       81,   81,   81,   92,   90,   71,  108,  105,   84,   91,
       72,   81,   81,   81,   81,   85,   78,   82,   89,   88,
      120,   86,   74,  207,   82,   82,   81,   81,   81,   81,

       92,   90,   81,   81,   81,   81,   91,  119,  119,  119,
       93,   96,   81,   81,   81,   81,   88,   94,   95,  207,
       64,   97,   81,   81,   81,   81,   59,   81,   81,   81,
       81,   98,  119,  119,  119,   99,   54,   52,   93,   96,
      100,  207,   50,   50,   94,   95,  207,  207,  207,   97,
       81,   81,   81,   81,  101,  207,  207,  102,  207,   98,
      207,  207,  207,   99,   81,   81,   81,   81,  100,  114,
      207,  114,  207,  104,  115,  115,  115,  115,  207,  207,
      207,  101,  103,  207,  102,  207,   68,  116,   69,   69,
       69,   69,  207,  207,   81,   81,   81,   81,  207,  207,

      207,  104,  207,  207,  207,   71,  207,  125,  103,  207,
       81,   81,   81,   81,  207,  116,   81,   81,   81,   81,
       81,   81,   81,   81,  207,  127,   81,   81,   81,   81,
      207,  207,  207,   71,  114,  125,  126,  207,  207,  207,
      129,  207,  128,  207,   81,   81,   81,   81,   81,   81,
       81,   81,  207,  127,   81,   81,   81,   81,   81,   81,
       81,   81,  207,  126,   81,   81,   81,   81,  129,  128,
      130,  207,  207,  132,  131,   81,   81,   81,   81,  207,
      133,   81,   81,   81,   81,   81,   81,   81,   81,  207,
      207,  134,   81,   81,   81,   81,  207,  130,  207,  207,

      132,  131,  207,  207,  207,  135,  207,  133,   81,   81,
       81,   81,  136,  207,  207,  207,  137,  207,  134,  138,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,  135,   81,   81,   81,   81,  207,  207,  136,
      207,  207,  139,  137,  207,  207,  207,  138,  141,  207,
      207,  140,  207,   81,   81,   81,   81,  207,  142,   81,
       81,   81,   81,   81,   81,   81,   81,  207,  207,  139,
      143,  146,  146,  146,  146,  141,  207,  207,  140,   81,
       81,   81,   81,  144,  114,  142,  114,  207,  145,  115,
      115,  115,  115,  207,   81,   81,   81,   81,  143,  114,

      207,  114,  116,  150,  146,  146,  146,  146,  207,  207,
      144,   81,   81,   81,   81,  145,   81,   81,   81,   81,
       81,   81,   81,   81,  151,  207,   81,   81,   81,   81,
      116,  150,  207,  207,  207,  154,  207,  207,  152,  155,
       81,   81,   81,   81,  207,  207,  153,  207,  207,  114,
      207,  207,  151,  156,   81,   81,   81,   81,   81,   81,
       81,   81,  207,  154,  114,  152,  207,  155,  207,  158,
      207,  207,  207,  153,  157,   81,   81,   81,   81,  207,
      207,  156,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,  207,  207,  207,  158,  159,  161,

      207,  157,  207,  207,  207,  160,  207,   81,   81,   81,
       81,  207,  207,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,  159,  162,  161,  163,  207,
      207,  207,  160,  207,  165,   81,   81,   81,   81,   81,
       81,   81,   81,  207,  207,  164,   81,   81,   81,   81,
      207,  207,  207,  162,  207,  207,  163,  207,  207,  168,
      207,  207,  165,  166,  207,  207,  167,   81,   81,   81,
       81,  207,  164,  146,  146,  146,  146,  170,  207,  170,
      207,  207,  171,  171,  171,  171,  207,  168,  207,  207,
      166,  207,  207,  167,   81,   81,   81,   81,   81,   81,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
      207,  207,  207,  172,  207,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,  207,  207,  173,   81,   81,   81,   81,  207,  207,
      172,  207,  170,  174,  175,   81,   81,   81,   81,   81,
       81,   81,   81,  207,  176,   81,   81,   81,   81,  207,
      173,  207,  207,   81,   81,   81,   81,  207,  207,  207,
      174,  175,  179,  207,  177,   81,   81,   81,   81,  207,
      178,  176,  207,   81,   81,   81,   81,  207,  180,  207,
      207,   81,   81,   81,   81,   81,   81,   81,   81,  207,

      179,  177,  182,  207,  207,  207,  183,  178,  181,   81,
       81,   81,   81,  207,  207,  207,  180,  207,  207,  207,
      184,   81,   81,   81,   81,  171,  171,  171,  171,  207,
      182,  207,  207,  207,  183,  181,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,  184,   81,
       81,   81,   81,   81,   81,   81,   81,  185,  207,   81,
       81,   81,   81,  207,  186,   81,   81,   81,   81,  187,
      207,  207,   81,   81,   81,   81,  207,  207,  207,  189,
       81,   81,   81,   81,  207,  185,  188,  190,  207,  207,
      207,  186,   81,   81,   81,   81,  207,  187,   81,   81,

       81,   81,   81,   81,   81,   81,  207,  189,   81,   81,
       81,   81,  207,  188,  191,  190,   81,   81,   81,   81,
       81,   81,   81,   81,  207,  192,  207,  207,  207,  193,
      195,  207,  194,  207,  207,   81,   81,   81,   81,  207,
      207,  191,   81,   81,   81,   81,  207,  196,   81,   81,
       81,   81,  192,  207,  207,  207,  193,  195,  197,  207,
      194,   81,   81,   81,   81,   81,   81,   81,   81,  207,
      198,  207,  207,  207,  196,  207,  207,  207,  199,   81,
       81,   81,   81,  207,  207,  197,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,  198,   81,

       81,   81,   81,  207,  207,  207,  199,   81,   81,   81,
       81,  207,   81,   81,   81,   81,   81,   81,   81,   81,
      207,  207,  200,  202,   81,   81,   81,   81,   81,   81,
       81,   81,  207,  207,  207,  201,  207,  203,  207,   81,
       81,   81,   81,  204,   81,   81,   81,   81,  207,  200,
      207,  202,  205,   81,   81,   81,   81,   81,   81,   81,
       81,  207,  201,  207,  207,  203,  207,  207,  207,  206,
      207,  204,   81,   81,   81,   81,  207,  207,  207,  207,
      205,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  206,   49,   49,

       49,   49,   49,   49,   49,   53,   53,   53,   58,   58,
       58,   82,   82,   82,  113,  207,  113,  113,  113,  113,
      113,  121,  207,  207,  121,   81,   81,   81,  148,  148,
      207,  148,    5,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207
    } ;

static const flex_int16_t yy_chk[1212] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    7,    7,
        8,    8,   12,   17,   19,   21,   47,   26,   28,   28,
       21,   51,   51,  121,   19,   17,   26,   26,   21,   12,

      216,   23,  169,   23,   23,   23,   23,   29,   29,   29,
       29,   30,   30,   30,   30,   70,   70,  117,  117,  121,
       23,   32,   32,   32,   32,  118,  118,   12,   22,  169,
       22,   22,   22,   22,   32,  122,   30,   80,   76,   47,
       22,   31,   31,   31,   31,   73,  121,   22,   23,   64,
       31,   70,   58,   22,   72,   72,   72,   31,   57,   35,
       34,   22,   32,   30,   31,   53,   35,   34,   22,   33,
       33,   33,   33,   35,   34,   22,   50,   45,   31,   34,
       22,   82,   82,   82,   82,   31,   27,   35,   34,   33,
       72,   31,   24,  148,   35,   34,   36,   36,   36,   36,

       35,   34,   37,   37,   37,   37,   34,  119,  119,  119,
       36,   37,   38,   38,   38,   38,   33,   36,   36,  148,
       20,   38,   39,   39,   39,   39,   16,   40,   40,   40,
       40,   39,  120,  120,  120,   39,   11,    9,   36,   37,
       40,    5,    4,    3,   36,   36,  148,    0,    0,   38,
       41,   41,   41,   41,   40,    0,    0,   40,    0,   39,
        0,    0,    0,   39,   42,   42,   42,   42,   40,   68,
        0,   68,    0,   42,   68,   68,   68,   68,    0,    0,
        0,   40,   41,    0,   40,    0,   69,   68,   69,   69,
       69,   69,    0,    0,   83,   83,   83,   83,    0,    0,

        0,   42,    0,    0,    0,   69,    0,   83,   41,    0,
       84,   84,   84,   84,    0,   68,   85,   85,   85,   85,
       86,   86,   86,   86,    0,   85,   87,   87,   87,   87,
        0,    0,    0,   69,   68,   83,   84,    0,    0,    0,
       87,    0,   86,    0,   88,   88,   88,   88,   90,   90,
       90,   90,    0,   85,   89,   89,   89,   89,   91,   91,
       91,   91,    0,   84,   92,   92,   92,   92,   87,   86,
       88,    0,    0,   90,   89,   93,   93,   93,   93,    0,
       91,   94,   94,   94,   94,   95,   95,   95,   95,    0,
        0,   92,   96,   96,   96,   96,    0,   88,    0,    0,

       90,   89,    0,    0,    0,   94,    0,   91,   97,   97,
       97,   97,   95,    0,    0,    0,   96,    0,   92,   97,
       98,   98,   98,   98,   99,   99,   99,   99,  100,  100,
      100,  100,   94,  101,  101,  101,  101,    0,    0,   95,
        0,    0,   98,   96,    0,    0,    0,   97,  100,    0,
        0,   99,    0,  102,  102,  102,  102,    0,  101,  103,
      103,  103,  103,  104,  104,  104,  104,    0,    0,   98,
      102,  114,  114,  114,  114,  100,    0,    0,   99,  132,
      132,  132,  132,  103,  115,  101,  115,    0,  104,  115,
      115,  115,  115,    0,  125,  125,  125,  125,  102,  116,

        0,  116,  115,  125,  116,  116,  116,  116,    0,    0,
      103,  126,  126,  126,  126,  104,  127,  127,  127,  127,
      128,  128,  128,  128,  126,    0,  129,  129,  129,  129,
      115,  125,    0,    0,    0,  129,    0,    0,  127,  129,
      130,  130,  130,  130,    0,    0,  128,    0,    0,  115,
        0,    0,  126,  130,  131,  131,  131,  131,  133,  133,
      133,  133,    0,  129,  116,  127,    0,  129,    0,  133,
        0,    0,    0,  128,  131,  134,  134,  134,  134,    0,
        0,  130,  135,  135,  135,  135,  136,  136,  136,  136,
      137,  137,  137,  137,    0,    0,    0,  133,  134,  136,

        0,  131,    0,    0,    0,  135,    0,  138,  138,  138,
      138,    0,    0,  139,  139,  139,  139,  140,  140,  140,
      140,  141,  141,  141,  141,  134,  138,  136,  139,    0,
        0,    0,  135,    0,  141,  142,  142,  142,  142,  143,
      143,  143,  143,    0,    0,  140,  144,  144,  144,  144,
        0,    0,    0,  138,    0,    0,  139,    0,    0,  144,
        0,    0,  141,  142,    0,    0,  143,  145,  145,  145,
      145,    0,  140,  146,  146,  146,  146,  149,    0,  149,
        0,    0,  149,  149,  149,  149,    0,  144,    0,    0,
      142,    0,    0,  143,  150,  150,  150,  150,  151,  151,

      151,  151,  152,  152,  152,  152,  153,  153,  153,  153,
        0,    0,    0,  150,    0,  154,  154,  154,  154,  155,
      155,  155,  155,  156,  156,  156,  156,  157,  157,  157,
      157,    0,    0,  153,  158,  158,  158,  158,    0,    0,
      150,    0,  149,  154,  155,  159,  159,  159,  159,  160,
      160,  160,  160,    0,  157,  161,  161,  161,  161,    0,
      153,    0,    0,  162,  162,  162,  162,    0,    0,    0,
      154,  155,  162,    0,  160,  163,  163,  163,  163,    0,
      161,  157,    0,  164,  164,  164,  164,    0,  163,    0,
        0,  165,  165,  165,  165,  166,  166,  166,  166,    0,

      162,  160,  165,    0,    0,    0,  166,  161,  164,  167,
      167,  167,  167,    0,    0,    0,  163,    0,    0,    0,
      167,  168,  168,  168,  168,  170,  170,  170,  170,    0,
      165,    0,    0,    0,  166,  164,  172,  172,  172,  172,
      173,  173,  173,  173,  174,  174,  174,  174,  167,  175,
      175,  175,  175,  176,  176,  176,  176,  173,    0,  177,
      177,  177,  177,    0,  174,  178,  178,  178,  178,  176,
        0,    0,  179,  179,  179,  179,    0,    0,    0,  178,
      180,  180,  180,  180,    0,  173,  177,  179,    0,    0,
        0,  174,  181,  181,  181,  181,    0,  176,  182,  182,

      182,  182,  183,  183,  183,  183,    0,  178,  185,  185,
      185,  185,    0,  177,  181,  179,  184,  184,  184,  184,
      186,  186,  186,  186,    0,  182,    0,    0,    0,  183,
      185,    0,  184,    0,    0,  187,  187,  187,  187,    0,
        0,  181,  188,  188,  188,  188,    0,  186,  191,  191,
      191,  191,  182,    0,    0,    0,  183,  185,  187,    0,
      184,  189,  189,  189,  189,  190,  190,  190,  190,    0,
      189,    0,    0,    0,  186,    0,    0,    0,  190,  192,
      192,  192,  192,    0,    0,  187,  193,  193,  193,  193,
      194,  194,  194,  194,  195,  195,  195,  195,  189,  196,

      196,  196,  196,    0,    0,    0,  190,  197,  197,  197,
      197,    0,  198,  198,  198,  198,  199,  199,  199,  199,
        0,    0,  195,  198,  200,  200,  200,  200,  201,  201,
      201,  201,    0,    0,    0,  197,    0,  200,    0,  202,
      202,  202,  202,  201,  203,  203,  203,  203,    0,  195,
        0,  198,  202,  204,  204,  204,  204,  205,  205,  205,
      205,    0,  197,    0,    0,  200,    0,    0,    0,  204,
        0,  201,  206,  206,  206,  206,    0,    0,    0,    0,
      202,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  204,  208,  208,

      208,  208,  208,  208,  208,  209,  209,  209,  210,  210,
      210,  211,  211,  211,  212,    0,  212,  212,  212,  212,
      212,  213,    0,    0,  213,  214,  214,  214,  215,  215,
        0,  215,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,

      207,  207,  207,  207,  207,  207,  207,  207,  207,  207,
      207
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[90] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 7 "lexer.l"
    #include <iostream>
    using namespace std;

#line 817 "lex.yy.c"

#line 819 "lex.yy.c"

#define INITIAL 0
#define CommentBlock 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 15 "lexer.l"

#line 1039 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 208 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1133 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "lexer.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "lexer.l"
{BEGIN(CommentBlock);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 18 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 19 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 26 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 27 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 28 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 29 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 30 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 31 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 32 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 33 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 34 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 35 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 36 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 37 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 38 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 39 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 40 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 41 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 42 "lexer.l"
{printf("token keyword - lexeme %s",yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 43 "lexer.l"
{printf("token identifier - lexema %s",yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 44 "lexer.l"
{printf("token interpreted string - lexema %s",yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 45 "lexer.l"
{printf("token raw string - lexema %s",yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 46 "lexer.l"
{printf("token integer literal - lexema %s",yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 47 "lexer.l"
{printf("token binary literal - lexema %s",yytext);} 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 48 "lexer.l"
{printf("token octadecimal literal - lexema %s",yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 49 "lexer.l"
{printf("token hexadecimal literal - lexema %s",yytext);}
	YY_BREAK
case 35:
#line 51 "lexer.l"
case 36:
#line 52 "lexer.l"
case 37:
#line 53 "lexer.l"
case 38:
YY_RULE_SETUP
#line 53 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 54 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 55 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 56 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 57 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 65 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 66 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 67 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 68 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 69 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 70 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 71 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 72 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 73 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 74 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 75 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 76 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 77 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 78 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 79 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 80 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 81 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 82 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 83 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 84 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 85 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 86 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 87 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 88 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 90 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 91 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 92 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 93 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 94 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 95 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 96 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 97 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 98 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 99 "lexer.l"
{ printf("token operato o punctuation - lexema %s",yytext);}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 100 "lexer.l"
;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 101 "lexer.l"
;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 102 "lexer.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 103 "lexer.l"
{  }
	YY_BREAK
case YY_STATE_EOF(CommentBlock):
#line 104 "lexer.l"
{ printf("Comentario de bloque no cerrado\n"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 105 "lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1548 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 208 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 208 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 207);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 105 "lexer.l"


int main(){
    yylex();
    return 0;
}
